name: DevSecOps

on:
    push:
        branches: [main]

jobs:

   # code stage (with shift left)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    #secrets Scanning
    secret-Scanning:  
        uses: ./.github/workflows/secret-scanning.yml 

     #Depedency Checks
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml  