name: DevSecOps

on:
  push:
    branches:
      - main

jobs:

  # Code Quality / Shift Left
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  # Secret Scanning
  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml

  # Dependency Scanning
  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  # Docker Security Scanning
  docker-scans:
    uses: ./.github/workflows/docker-scans.yml
    secrets: inherit

  # SonarQube Scan
  sonar-qube:
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit